apiVersion: apps/v1
kind: Deployment
metadata:
  name: trace-deployment-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trace-deployment-test
  template:
    metadata:
      labels:
        app: trace-deployment-test
    spec:
      containers:
      - image: ucsdcmi/tracealgo:python3.8
        imagePullPolicy: Always
        name: tracealgorithm
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30