# trace-deployment.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: trace-deployment
spec:
  selector:
    matchLabels:
      app: trace-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: trace-deployment
    spec:
      containers:
        - name: trace
          image: yizong/trace_algo
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 10m
              memory: 80Mi
            requests:
              cpu: 10m
              memory: 80Mi
          ports:
            - containerPort: 8080
              name: "http-server"
---
apiVersion: v1
kind: Service
metadata:
  name: trace
spec:
  ports:
    - name: client
      port: 8080
  selector:
    app: trace-deployment
